# configs/segmentation/eval.yaml

dataset:
  path: /home/at83760/workspace/Dataset/HCP_OASIS
  split_file: /home/at83760/workspace/fifth_semester/SimCortex/data/combined_dataset_split.csv

trainer:
  device: cuda:0        # used to pick CPU vs GPU for metric computation
  num_workers: 2        # DataLoader workers
  img_batch_size: 1     # batch size for evaluation

outputs:
  pred_save_dir: /home/at83760/workspace/fifth_semester/SimCortex/ckpts/segmentation_model/exp1/predictions
  eval_save_dir: /home/at83760/workspace/fifth_semester/SimCortex/ckpts/segmentation_model/exp1/eval

hydra:
  run:
    dir: .              # stay in your project root
  output_subdir: null
