# configs/segmentation/predict.yaml

dataset:
  path: /home/at83760/workspace/Dataset/HCP_OASIS
  split_file: /home/at83760/workspace/fifth_semester/SimCortex/data/combined_dataset_split.csv
  predict_split_name: test    

trainer:
  device: cuda:0
  num_workers: 2

model:
  in_channels: 1
  out_channels: 9

outputs:
  model_path: /home/at83760/workspace/fifth_semester/SimCortex/ckpts/segmentation_model/exp1/model_seg_hcp-oasis.pt
  pred_save_dir: /home/at83760/workspace/fifth_semester/SimCortex/ckpts/segmentation_model/exp1/predictions
  
hydra:
  run:
    dir: .
  output_subdir: null
