# configs/segmentation/train.yaml

dataset:
  path: /home/at83760/workspace/Dataset/HCP_OASIS
  split_file: /home/at83760/workspace/fifth_semester/SimCortex/data/combined_dataset_split.csv
  train_split_name: train
  val_split_name: val

trainer:
  device: cuda:0
  num_epochs: 1000
  learning_rate: 0.0001
  img_batch_size: 10
  num_workers: 2
  validation_interval: 2
  tag: exp2         

model:
  name: Unet       # not used programmatically, but harmless
  in_channels: 1
  out_channels: 9

experiment:
  name: hcp-oasis
  output_dir: /home/at83760/workspace/fifth_semester/SimCortex/ckpts/segmentation_model
  exp_number: 2
  train_type: seg  # no longer checked in train_one(), but okay to leave

outputs:
  log_dir: ${experiment.output_dir}/exp${experiment.exp_number}/logs
  model_path: ${experiment.output_dir}/exp${experiment.exp_number}/model_seg_${experiment.name}_${trainer.tag}.pt

hydra:
  run:
    dir: ${outputs.log_dir}
  output_subdir: null
