from __future__ import annotations
import math
import torch
import torch.nn as nn
import torch.nn.functional as F





class ConvGNAct(nn.Module):
    """
    Conv3D + GroupNorm + LeakyReLU (+ optional Dropout3D)
    Works better than BatchNorm with small batch sizes.
    """
    def __init__(self, cin, cout, k=3, s=1, groups=8, dropout=0.0):
        super().__init__()
        p = k // 2  # k=3 -> p=1
        self.conv = nn.Conv3d(cin, cout, kernel_size=k, stride=s, padding=p, bias=False)

        g = min(groups, cout)
        while g > 1 and (cout % g) != 0:
            g -= 1
        self.gn = nn.GroupNorm(g, cout)
        self.act = nn.LeakyReLU(0.2, inplace=True)
        self.do = nn.Dropout3d(dropout) if dropout > 0 else nn.Identity()

    def forward(self, x):
        x = self.conv(x)
        x = self.gn(x)
        x = self.act(x)
        x = self.do(x)
        return x


class ResBlock3D(nn.Module):
    """
    Lightweight residual block.
    """
    def __init__(self, c, k=3, groups=8, dropout=0.0):
        super().__init__()
        self.b1 = ConvGNAct(c, c, k=k, s=1, groups=groups, dropout=dropout)
        self.b2 = ConvGNAct(c, c, k=k, s=1, groups=groups, dropout=dropout)

    def forward(self, x):
        return x + self.b2(self.b1(x))


class GaussianFilter(nn.Module):

    def __init__(
        self,
        C: int = 3,
        sigma: float = 1.0,
        truncate: float = 2.0,
        padding_mode: str = "replicate",
    ):
        super().__init__()
        if sigma <= 0:
            raise ValueError(f"sigma must be > 0, got {sigma}")

        self.C = int(C)
        self.sigma = float(sigma)
        self.truncate = float(truncate)
        self.padding_mode = str(padding_mode)

        radius = max(1, int(math.ceil(self.truncate * self.sigma)))
        coords = torch.arange(-radius, radius + 1, dtype=torch.float32)
        zz, yy, xx = torch.meshgrid(coords, coords, coords, indexing="ij")

        kernel = torch.exp(
            -(xx * xx + yy * yy + zz * zz) / (2.0 * self.sigma * self.sigma)
        )
        kernel = kernel / kernel.sum()
        kernel = kernel[None, None].repeat(self.C, 1, 1, 1, 1)

        self.register_buffer("kernel", kernel)
        self.radius = radius

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x = F.pad(x, (self.radius,) * 6, mode=self.padding_mode)
        return F.conv3d(x, weight=self.kernel, padding=0, groups=self.C)

class GeomInject(nn.Module):
    """
    Stable fusion: f = m + gate * proj(g)
    gate is learnable scalar (per-level) initialized very small => starts MRI-only, then learns to use geom.
    """
    def __init__(self, c_mri: int, c_geom: int, gate_init: float = -3.0):
        super().__init__()
        self.proj = nn.Conv3d(c_geom, c_mri, kernel_size=1, bias=True)
        self.gate_logit = nn.Parameter(torch.tensor(gate_init, dtype=torch.float32))

    def forward(self, m, g):
        gate = torch.sigmoid(self.gate_logit)  # ~0.018 at -4.0
        return m + gate * self.proj(g)


# -------------------------
# Dual-Encoder U-Net that outputs multi-scale SVFs
# -------------------------
class DualMUNetV2(nn.Module):
    """
    True dual encoder:
      - MRI encoder (full)
      - Geom/prob encoder (lighter + optional shallow depth)
    Fusion is done at each level via GeomInject (stable, reduces overfit risk).

    geom_depth:
      1..6 : number of learned geom stages
      if <6, deeper geom features are generated by pooling (no extra params).
    """
    def __init__(
        self,
        C_in: int = 2,                    # [MRI] + geom channels
        C_hid=(8, 16, 32, 64, 128, 128),
        geom_ratio: float = 0.5,          # geom width ratio
        geom_depth: int = 6,              # 1..6 learned geometry stages
        K: int = 3,
        gn_groups: int = 8,
        gate_init: float = -3.0,
        dropout: float = 0.0,
    ):
        super().__init__()
        C_in = int(C_in)
        if C_in < 2:
            raise ValueError(f"C_in must be >= 2 for [MRI + geom/prob], got {C_in}")

        geom_depth = int(geom_depth)
        if not (1 <= geom_depth <= 6):
            raise ValueError(f"geom_depth must be in [1, 6], got {geom_depth}")

        geom_ratio = float(geom_ratio)
        if not math.isfinite(geom_ratio) or geom_ratio <= 0.0:
            raise ValueError(f"geom_ratio must be finite and > 0, got {geom_ratio}")

        gn_groups = int(gn_groups)
        if gn_groups <= 0:
            raise ValueError(f"gn_groups must be > 0, got {gn_groups}")

        gate_init = float(gate_init)
        if not math.isfinite(gate_init):
            raise ValueError(f"gate_init must be finite, got {gate_init}")

        dropout = float(dropout)
        if not (0.0 <= dropout < 1.0):
            raise ValueError(f"dropout must satisfy 0 <= dropout < 1, got {dropout}")

        self.C_in = C_in

        # MRI channels
        Cm = list(C_hid)
        if len(Cm) != 6:
            raise ValueError(f"C_hid must contain exactly 6 channel values, got {len(Cm)}: {Cm}")
        # Geom channels (smaller)
        Cg = [max(4, int(c * geom_ratio)) for c in Cm]

        self.geom_depth = geom_depth

        # ---- MRI encoder (6 stages) ----
        self.m1 = nn.Sequential(ConvGNAct(1,   Cm[0], k=K, s=1, groups=gn_groups), ResBlock3D(Cm[0], k=K, groups=gn_groups))
        self.m2 = nn.Sequential(ConvGNAct(Cm[0], Cm[1], k=K, s=1, groups=gn_groups), ResBlock3D(Cm[1], k=K, groups=gn_groups))
        self.m3 = nn.Sequential(ConvGNAct(Cm[1], Cm[2], k=K, s=2, groups=gn_groups), ResBlock3D(Cm[2], k=K, groups=gn_groups))  # /2
        self.m4 = nn.Sequential(ConvGNAct(Cm[2], Cm[3], k=K, s=2, groups=gn_groups), ResBlock3D(Cm[3], k=K, groups=gn_groups, dropout=dropout))  # /4
        self.m5 = nn.Sequential(ConvGNAct(Cm[3], Cm[4], k=K, s=2, groups=gn_groups), ResBlock3D(Cm[4], k=K, groups=gn_groups, dropout=dropout))  # /8
        self.m6 = nn.Sequential(ConvGNAct(Cm[4], Cm[5], k=K, s=1, groups=gn_groups), ResBlock3D(Cm[5], k=K, groups=gn_groups, dropout=dropout))

        # ---- Geom encoder (up to geom_depth stages learned) ----
        # stage 1 is always learned
        self.g1 = nn.Sequential(
            ConvGNAct(C_in - 1, Cg[0], k=K, s=1, groups=gn_groups),
            ResBlock3D(Cg[0], k=K, groups=gn_groups),
        )
        # build optional learned stages
        self.g2 = nn.Sequential(
            ConvGNAct(Cg[0], Cg[1], k=K, s=1, groups=gn_groups),
            ResBlock3D(Cg[1], k=K, groups=gn_groups),
        ) if geom_depth >= 2 else None
        self.g3 = nn.Sequential(
            ConvGNAct(Cg[1], Cg[2], k=K, s=2, groups=gn_groups),
            ResBlock3D(Cg[2], k=K, groups=gn_groups),
        ) if geom_depth >= 3 else None
        self.g4 = nn.Sequential(
            ConvGNAct(Cg[2], Cg[3], k=K, s=2, groups=gn_groups),
            ResBlock3D(Cg[3], k=K, groups=gn_groups),
        ) if geom_depth >= 4 else None
        self.g5 = nn.Sequential(
            ConvGNAct(Cg[3], Cg[4], k=K, s=2, groups=gn_groups),
            ResBlock3D(Cg[4], k=K, groups=gn_groups),
        ) if geom_depth >= 5 else None
        self.g6 = nn.Sequential(
            ConvGNAct(Cg[4], Cg[5], k=K, s=1, groups=gn_groups),
            ResBlock3D(Cg[5], k=K, groups=gn_groups),
        ) if geom_depth >= 6 else None

        # ---- Fusion injectors (per level) ----
        self.f1 = GeomInject(Cm[0], Cg[0], gate_init=gate_init)
        self.f2 = GeomInject(Cm[1], Cg[1] if geom_depth >= 2 else Cg[0], gate_init=gate_init)
        self.f3 = GeomInject(Cm[2], Cg[2] if geom_depth >= 3 else (Cg[1] if geom_depth >= 2 else Cg[0]), gate_init=gate_init)
        self.f4 = GeomInject(Cm[3], Cg[3] if geom_depth >= 4 else (Cg[2] if geom_depth >= 3 else (Cg[1] if geom_depth >= 2 else Cg[0])), gate_init=gate_init)
        self.f5 = GeomInject(Cm[4], Cg[4] if geom_depth >= 5 else (Cg[3] if geom_depth >= 4 else (Cg[2] if geom_depth >= 3 else (Cg[1] if geom_depth >= 2 else Cg[0]))), gate_init=gate_init)
        self.f6 = GeomInject(Cm[5], Cg[5] if geom_depth >= 6 else (Cg[4] if geom_depth >= 5 else (Cg[3] if geom_depth >= 4 else (Cg[2] if geom_depth >= 3 else (Cg[1] if geom_depth >= 2 else Cg[0])))), gate_init=gate_init)

        # ---- Decoder (uses fused skips) ----
        self.up = nn.Upsample(scale_factor=2, mode="trilinear", align_corners=True)

        self.d5 = nn.Sequential(ConvGNAct(Cm[5] + Cm[4], Cm[4], k=K, s=1, groups=gn_groups), ResBlock3D(Cm[4], k=K, groups=gn_groups, dropout=dropout))
        self.d4 = nn.Sequential(ConvGNAct(Cm[4] + Cm[3], Cm[3], k=K, s=1, groups=gn_groups), ResBlock3D(Cm[3], k=K, groups=gn_groups, dropout=dropout))
        self.d3 = nn.Sequential(ConvGNAct(Cm[3] + Cm[2], Cm[2], k=K, s=1, groups=gn_groups), ResBlock3D(Cm[2], k=K, groups=gn_groups))
        self.d2 = nn.Sequential(ConvGNAct(Cm[2] + Cm[1], Cm[1], k=K, s=1, groups=gn_groups), ResBlock3D(Cm[1], k=K, groups=gn_groups))
        self.d1 = nn.Sequential(ConvGNAct(Cm[1] + Cm[0], Cm[0], k=K, s=1, groups=gn_groups), ResBlock3D(Cm[0], k=K, groups=gn_groups))

        # ---- Multi-scale flow heads ----
        self.flow1 = nn.Conv3d(Cm[3], 3, K, 1, padding=K // 2)
        self.flow2 = nn.Conv3d(Cm[2], 3, K, 1, padding=K // 2)
        self.flow3 = nn.Conv3d(Cm[1], 3, K, 1, padding=K // 2)
        self.flow4 = nn.Conv3d(Cm[0], 3, K, 1, padding=K // 2)

        for layer in [self.flow1, self.flow2, self.flow3, self.flow4]:
            nn.init.normal_(layer.weight, 0, 1e-5)
            nn.init.constant_(layer.bias, 0.0)

    def _geom_pool(self, g, times: int):
        # downsample by factor 2^times using avg pooling (no parameters)
        for _ in range(times):
            g = F.avg_pool3d(g, kernel_size=2, stride=2)
        return g

    def forward(self, x):
        if x.ndim != 5:
            raise ValueError(f"DualMUNetV2 expects a 5D tensor (B,C,D,H,W), got {tuple(x.shape)}")
        if int(x.shape[1]) != self.C_in:
            raise ValueError(
                f"DualMUNetV2 expected {self.C_in} input channels, got {int(x.shape[1])}"
            )

        mri = x[:, 0:1]     # (B,1,D,H,W)
        geom = x[:, 1:]     # (B,C_in-1,D,H,W)

        # ----- MRI encoder -----
        m1 = self.m1(mri)      # full
        m2 = self.m2(m1)       # full
        m3 = self.m3(m2)       # /2
        m4 = self.m4(m3)       # /4
        m5 = self.m5(m4)       # /8
        m6 = self.m6(m5)       # /8

        # ----- Geom encoder (learned up to geom_depth) -----
        g1 = self.g1(geom)     # full

        if self.geom_depth >= 2:
            g2 = self.g2(g1)   # full
        else:
            g2 = g1

        if self.geom_depth >= 3:
            g3 = self.g3(g2)   # /2
        else:
            # if not learned, make it by pooling
            g3 = self._geom_pool(g2, times=1)

        if self.geom_depth >= 4:
            g4 = self.g4(g3)   # /4
        else:
            g4 = self._geom_pool(g3, times=1)

        if self.geom_depth >= 5:
            g5 = self.g5(g4)   # /8
        else:
            g5 = self._geom_pool(g4, times=1)

        if self.geom_depth >= 6:
            g6 = self.g6(g5)   # /8
        else:
            g6 = g5

        # ----- Fusion (stable inject) -----
        f1 = self.f1(m1, g1)
        f2 = self.f2(m2, g2)
        f3 = self.f3(m3, g3)
        f4 = self.f4(m4, g4)
        f5 = self.f5(m5, g5)
        f6 = self.f6(m6, g6)

        # ----- Decoder -----
        x = torch.cat([f6, f5], dim=1)  # /8
        x = self.d5(x)
        x = self.up(x)                  # /4

        x = torch.cat([x, f4], dim=1)   # /4
        x = self.d4(x)
        svf1 = self.up(self.up(self.flow1(x)))  # /4 -> full

        x = self.up(x)                  # /2
        x = torch.cat([x, f3], dim=1)   # /2
        x = self.d3(x)
        svf2 = self.up(self.flow2(x))   # /2 -> full

        x = self.up(x)                  # full
        x = torch.cat([x, f2], dim=1)   # full
        x = self.d2(x)
        svf3 = self.flow3(x)            # full

        x = torch.cat([x, f1], dim=1)   # full
        x = self.d1(x)
        svf4 = self.flow4(x)            # full

        return svf1, svf2, svf3, svf4

# -------------------------
# SurfDeform (same logic, but uses DualMUNetV2)
# -------------------------
class SurfDeform(nn.Module):
    def __init__(
        self,
        C_in=2,
        C_hid=(8, 16, 32, 64, 128, 128),
        inshape=(184, 224, 184),
        sigma=1.0,
        # dual encoder controls
        geom_ratio=0.5,
        geom_depth=6,
        gn_groups=8,
        gate_init =-3.0,
        dropout=0.0,
    ):
        super().__init__()
        self.inshape = tuple(int(value) for value in inshape)
        self.C_in = int(C_in)

        if len(self.inshape) != 3:
            raise ValueError(f"inshape must be a 3-tuple/list (D,H,W), got {self.inshape}")

        if any(value <= 0 or value % 8 != 0 for value in self.inshape):
            raise ValueError(
                "SurfDeform inshape must contain positive dimensions divisible by 8, "
                f"got {self.inshape}"
            )

        self.munet = DualMUNetV2(
            C_in=C_in,
            C_hid=C_hid,
            geom_ratio=geom_ratio,
            geom_depth=geom_depth,
            gn_groups=gn_groups,
            gate_init=gate_init,
            dropout=dropout,
        )

        self.gaussian = GaussianFilter(
            C=3,
            sigma=sigma,
            truncate=2.0,
            padding_mode="replicate",
        )
        self._grid_cache = {}

    def forward(
        self,
        vert: torch.Tensor,
        vol: torch.Tensor,
        n_steps: int,
    ):
        if vert.ndim != 3 or int(vert.shape[-1]) != 3:
            raise ValueError(f"vert must have shape (B,V,3), got {tuple(vert.shape)}")
        if vol.ndim != 5:
            raise ValueError(f"vol must have shape (B,C,D,H,W), got {tuple(vol.shape)}")
        if int(vert.shape[0]) != int(vol.shape[0]):
            raise ValueError(
                f"vert/vol batch mismatch: {int(vert.shape[0])} vs {int(vol.shape[0])}"
            )
        if int(vol.shape[1]) != self.C_in:
            raise ValueError(f"Input vol has {int(vol.shape[1])} channels, expected {self.C_in}")
        if tuple(vol.shape[2:]) != self.inshape:
            raise ValueError(f"Input vol shape {tuple(vol.shape[2:])} != inshape {self.inshape}")
        n_steps = int(n_steps)
        if n_steps < 0:
            raise ValueError(f"n_steps must be >= 0, got {n_steps}")

        svfs = self.munet(vol)

        for svf in svfs:
            svf = self.gaussian(svf)
            phi = self.integrate(svf, n_steps)

            deform = self.interpolate(
                vert[:, :, None, None],
                phi,
            )[..., 0, 0].permute(0, 2, 1)

            vert = vert + deform

        return vert


    def _get_base_grid(self, shape, ref: torch.Tensor) -> torch.Tensor:
        D, H, W = [int(v) for v in shape]
        key = (D, H, W, ref.device.type, ref.device.index, ref.dtype)

        grid = self._grid_cache.get(key, None)
        if grid is None:
            zz, yy, xx = torch.meshgrid(
                torch.arange(D, device=ref.device, dtype=ref.dtype),
                torch.arange(H, device=ref.device, dtype=ref.dtype),
                torch.arange(W, device=ref.device, dtype=ref.dtype),
                indexing="ij",
            )
            grid = torch.stack((zz, yy, xx), dim=0)[None]  # (1,3,D,H,W), IJK/DHW
            self._grid_cache[key] = grid

        return grid


    def transform(self, src: torch.Tensor, flow: torch.Tensor) -> torch.Tensor:
        base = self._get_base_grid(flow.shape[2:], flow)
        coord = (base + flow).permute(0, 2, 3, 4, 1)  # (B,D,H,W,3), IJK
        return self.interpolate(coord, src)


    def integrate(self, svf: torch.Tensor, n_steps: int = 7) -> torch.Tensor:
        n_steps = int(n_steps)
        if n_steps < 0:
            raise ValueError(f"n_steps must be >= 0, got {n_steps}")
        if svf.ndim != 5 or int(svf.shape[1]) != 3:
            raise ValueError(f"svf must have shape (B,3,D,H,W), got {tuple(svf.shape)}")

        flow = svf / float(2 ** n_steps)
        for _ in range(n_steps):
            flow = flow + self.transform(flow, flow)
        return flow

    def interpolate(self, coord_ijk: torch.Tensor, src: torch.Tensor) -> torch.Tensor:
        """
        coord_ijk: (..., 3) in IJK / DHW voxel coordinates of src
        src: (B, C, D, H, W)
        """
        D, H, W = src.shape[2:]

        d = 2.0 * coord_ijk[..., 0] / max(D - 1, 1) - 1.0
        h = 2.0 * coord_ijk[..., 1] / max(H - 1, 1) - 1.0
        w = 2.0 * coord_ijk[..., 2] / max(W - 1, 1) - 1.0

        # grid_sample expects XYZ = WHD for 5D input
        grid_xyz = torch.stack((w, h, d), dim=-1)

        return F.grid_sample(
            src,
            grid_xyz,
            mode="bilinear",
            padding_mode="border",
            align_corners=True,
        )
