# configs/initial_surf/generate.yaml

# device on which to run the Unet inference
device: cuda:0

# segmentation model checkpoint directory (must contain your .pt file)
model_seg_dir: /home/at83760/workspace/fifth_semester/SimCortex/ckpts/segmentation_model/exp1

# path to your CSV that lists ‘subject,split’
csv_split_path: /home/at83760/workspace/fifth_semester/SimCortex/data/combined_dataset_split.csv

# base data folder (each subfolder is one subject)
data_dir: /home/at83760/workspace/Dataset/HCP_OASIS

# where to write out the ini_*.ply and mask NIfTIs
result_dir: /home/at83760/workspace/fifth_semester/SimCortex/ckpts/initial_surfacesTEST

# marching‐cubes / smoothing parameters
mesh:
  sigma:   0.5
  alpha:   16
  n_smooth: 2

# Level‐search parameters (collision‐driven)
levels:
  pial_start:   -0.1    # initial isovalue for pial
  pial_step:     0.05   # decrement if collision
  white_offset:  0.1    # how far below pial to start white

# which surfaces to extract (you only support "all" right now)
target_surface: all

# Hydra boilerplate—if you ever switch generate.py to use @hydra.main
hydra:
  run:
    dir: ${result_dir}
  output_subdir: null
