user_config: null

dataset:
  pred_dir: /home/at83760/workspace/fifth_semester/SimCortex/ckpts/surface_model/exp1/predict
  gt_base_dir: /home/at83760/workspace/Dataset/HCP_OASIS
  surface_names: ['lh_pial', 'lh_white', 'rh_pial', 'rh_white']
  
  
eval:
  n_chamfer: 150000
  n_assd_hd: 150000
  device: 'cuda:0'
  log_level: INFO
  output_dir: /home/at83760/workspace/fifth_semester/SimCortex/ckpts/surface_model/exp1/eval



hydra:
  run:
    dir: ${eval.output_dir}
  output_subdir: null

