# configs/surf_recon/predict.yaml

# Inference settings (under `predict` namespace)
predict:
  checkpoint_path: /home/at83760/workspace/fifth_semester/SimCortex/ckpts/Reconstraction_Surface_Model/exp1/model/best_model.pth
  output_dir:      /home/at83760/workspace/fifth_semester/SimCortex/ckpts/Reconstraction_Surface_Model/exp2
  img_batch_size:  1
  device:          cuda:0
  points_per_image: 150000
  num_workers:     2
  log_level:       INFO

# Dataset settings
dataset:
  path:                /home/at83760/workspace/Dataset/HCP_OASIS
  split_file:         /home/at83760/workspace/Dataset/combined_dataset_split.csv
  initial_surface_path:  /home/at83760/workspace/fifth_semester/Topology-Project/ckpts/Reconstraction_Surface_Model/exp1/ini_surfaces
  test_split_name:    test
  surface_name:       ['lh_pial','lh_white','rh_pial','rh_white']

# Model hyperparameters
model:
  sigma:   1
  n_steps: 7
  inshape: [184,224,184]
  c_hid:   [8,16,32,64,128,128]

# Loss weights (if needed downstream)
objective:
  chamfer_weight: 1
  edge_loss_weight: 0.7
  normal_weight: 0.7

# Hydra boilerplate
hydra:
  run:
    dir: ${predict.output_dir}
  output_subdir: null