user_config: null

dataset:  
  path: /home/at83760/workspace/Dataset/HCP_OASIS
  split_file: /home/at83760/workspace/Dataset/combined_dataset_split.csv
  initial_surface_path: /home/at83760/workspace/fifth_semester/Topology-Project/ckpts/Reconstraction_Surface_Model/exp1/ini_surfaces
  train_split_name: train
  val_split_name: val
  surface_name: ["lh_pial","lh_white","rh_pial","rh_white"]

trainer:
  img_batch_size: 5
  device: 'cuda:0'
  num_epochs: 500 
  validation_interval: 10
  learning_rate: 0.0001
  points_per_image: 150000
  num_workers: 2
  log_level: INFO  


model:
  sigma: 1
  n_steps: 7
  inshape: [184, 224, 184]
  c_hid: [8,16,32,64,128,128]

objective:
  chamfer_weight: 1
  edge_loss_weight: 0.7
  normal_weight: 0.7

outputs:
  output_dir: /home/at83760/workspace/fifth_semester/SimCortex/ckpts/Reconstraction_Surface_Model/exp2

hydra:
  run:
    dir: ${outputs.output_dir}
  output_subdir: null